### ISSUE TITLE
Could we make this repo public? 

### ISSUE THREAD

**Issue by Charlie-George** [sims-lab/ccb-wiki#2]
There is lots of info on here that is useful for any user of CCB cluster using cgatcore 
- I've already forwarded half of this info to others.- It would be useful just to direct them here.

**Comment by kevinrue** [comment]
Probably want to tag @david-cgat

**Comment by david-cgat** [comment]
Fine with me, but probably want to call it CCB not CBRG?

**Comment by Charlie-George** [comment]
@kevinrue @david-cgat  I don't have permissions for this - but i think you both do.... 

Thanks

**Comment by kevinrue** [comment]
Done: renamed and made public
